# Generated by Django 5.1 on 2024-09-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_mimodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
