# Generated by Django 5.1 on 2024-09-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_delete_mimodelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='registro',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='ping',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='ping',
            name='timestamp',
            field=models.DateTimeField(default='0.0.0.0'),
        ),
    ]
