# Generated by Django 5.1 on 2024-09-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_rename_registro_ping_mensaje_ping_ip_ping_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
