# Generated by Django 5.1 on 2024-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_ping_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='ping',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
