# Generated by Django 5.1 on 2024-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_alter_ping_ip_alter_ping_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
