# Generated by Django 5.1 on 2024-09-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_ping_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='usuario',
        ),
    ]
