# Generated by Django 5.1 on 2024-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_ping_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
