# Generated by Django 5.1 on 2024-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_alter_ping_ip_alter_ping_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquear',
            options={'verbose_name': 'Bloquear trafico', 'verbose_name_plural': 'Bloqueos de trafico'},
        ),
        migrations.AlterModelOptions(
            name='dnsquery',
            options={'verbose_name': 'Consulta Dns', 'verbose_name_plural': 'Consultas Dns'},
        ),
        migrations.AlterModelOptions(
            name='permitir',
            options={'verbose_name': 'Permitir trafico', 'verbose_name_plural': 'Permitir trafico'},
        ),
        migrations.AlterModelOptions(
            name='ping',
            options={'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
        migrations.AlterModelOptions(
            name='registroactividad',
            options={'verbose_name': 'Registro de actividad', 'verbose_name_plural': 'Registro de actividades'},
        ),
        migrations.AddField(
            model_name='ping',
            name='protocolo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
