# Generated by Django 5.1 on 2024-10-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_alter_ping_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='usuario',
        ),
    ]
