from aplicacion import FirewallRule

def generate_nftables_config():
    rules = FirewallRule.objects.all()

    with open('/etc/nftables/firewall.conf', 'w') as config_file:
        config_file.write('# Generated by Django Firewall App\n')
        config_file.write('table ip filter {\n')
        config_file.write('    chain input {\n')
        config_file.write('        type filter hook input priority 0; policy drop;\n')
        
        for rule in rules:
            config_file.write('ip saddr {rule.url} udp dport {rule.port} drop')
        
        config_file.write('    }\n')
        config_file.write('}\n')

generate_nftables_config()
